CREATE TABLE nurse (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    phone VARCHAR(20),
    email VARCHAR(255),
    instagram VARCHAR(255),
    facebook VARCHAR(255),
    twitter VARCHAR(255),
    linkedin VARCHAR(255),
    birthday DATE,
    gender VARCHAR(10),
    coren VARCHAR(20),
    specialties JSON,
    lgpd BOOLEAN,
    zipCode VARCHAR(10),
    type VARCHAR(50),
    street VARCHAR(255),
    district VARCHAR(255),
    complement VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    country VARCHAR(100),
    number VARCHAR(20),
    latitude DOUBLE,
    longitude DOUBLE,
    exactLocation BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
