version: '3.9'

services:
  db:
    image: mysql:5
    container_name: localizaenfpics_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - localizaenfpics_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=root_password"]
      interval: 2s
      timeout: 2s
      retries: 7

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: localizaenfpics_backend
    environment:
      DB_URL: $DB_URL
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
    ports:
      - "8080:80"
    volumes:
      - ./backend:/home/nimmis
    depends_on:
      db:
        condition: service_healthy
    networks:
      - localizaenfpics_network
    command: ["sh", "-c", "php migrate.php && php -S 0.0.0.0:80 -t ."]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: localizaenfpics_frontend
    environment:
      VITE_BACKEND_URL: $BACKEND_URL
      VITE_BACKEND_PORT: $BACKEND_PORT
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - localizaenfpics_network
    depends_on:
      - backend

volumes:
  db_data:

networks:
  localizaenfpics_network:
