version: '3.9'

services:
  db:
    image: mysql:5
    container_name: localizaenfpics_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: localizaenfpics_backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/home/nimmis
    depends_on:
      - db
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
