export type Address = {
  road: string,
  hamlet?: string,
  city_district?: string,
  city?: string,
  county?: string,
  ISO3166_2_lvl6?: string,
  state?: string,
  ISO3166_2_lvl4?: string,
  postcode?: string,
  country: string,
  country_code: string,
  quarter?: string,
  suburb?: string,
}

export type Location = {
  place_id: number,
  licence: string,
  osm_type: string,
  osm_id: number,
  lat: string,
  lon: string,
  class: string,
  type: string,
  place_rank: number,
  importance: number,
  addresstype: string,
  name: string,
  display_name: string,
  address: Address,
  boundingbox: [string, string, string, string],
}